### PR TITLE
Add a config option EventTag that is added as a tag to all reported events

### PR DESCRIPTION
**Pull request by milescrabill**
It's just a string, and is really only applicable to the Datadog EventReporter

### CODE REVIEW

**Comment by whd** [comment]
I think this is pretty datadog-specific, and therefore the configuration for it should be under the datadog configuration and you shouldn't need to pass it around everywhere to `NewStatistic`.

**Comment by milescrabill** [comment]
If we're going to support  tags for events beyond Datadog, we should
support the EventTag more broadly as well.

**Comment by whd** [comment]
Datadog tags are not AWS tags. In this case it makes more sense to me to leave this specific configuration of additional datadog tags to the datadog event reporter. Otherwise, we are defining our own tag abstraction that is distinct from but related to both Datadog tags and AWS tags (which is fine, but I think unnecessary).

**Comment by milescrabill** [comment]
I'm leaving it. 😒

**Pull request merged**
